# Generated by Django 4.1.13 on 2025-06-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Line', 'Line'), ('Arc', 'Arc'), ('Circle', 'Circle'), ('Cube', 'Cube'), ('Cylinder', 'Cylinder'), ('Sphere', 'Sphere')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('parameters', models.JSONField()),
            ],
        ),
    ]
